### ISSUE TITLE
[BUG] mobilenet_v1_1.0_224.tflite model parse failure

### ISSUE THREAD

**Issue by huangteng** [alibaba/heterogeneity-aware-lowering-and-optimization#65] opened 2020-12-07 03:42 UTC
**Describe the bug**

**To Reproduce**
build/bin/halo -disable-broadcasting -fuse-conv-bias -exec-mode=interpret -emit-value-id-as-int -emit-data-as-c -target cxx ./mobilenet_v1_1.0_224.tflite -o ./mobilenet_v1_1.cc

**Expected behavior**
could not parse mobilenet_v1_1.0_224.tflite (file is in attachment, rename to .tflite to run)

**Screenshots**
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1207 03:39:29.349206 34502 tflite_parser.cc:273] Convert function not found, Please check if it is supported: Op: [43], Index: [-1]
root# /build/bin/halo -fuse-conv-bias -exec-mode=interpret -emit-value-id-as-int -emit-data-as-c -target cxx ./mobilenet_v1_1.0_224.tflite -o ./mobilenet_v1_1.cc
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1207 03:40:06.268330 34503 tflite_parser.cc:273] Convert function not found, Please check if it is supported: Op: [43], Index: [-1]

[mobilenet_v1_1.0_224.tflite.txt](https://github.com/alibaba/heterogeneity-aware-lowering-and-optimization/files/5656559/mobilenet_v1_1.0_224.tflite.txt)

**Comment by youbeny** [comment] 2020-12-08 07:53
the root cause is tflite squeeze op is not supportted yet, now fixed，see https://github.com/alibaba/heterogeneity-aware-lowering-and-optimization/pull/71

**Closed** 2020-12-08 22:12 UTC
